### ISSUE TITLE
Failed to run custom build command

### ISSUE THREAD

**Issue by nabaruns** [osmosis-labs/test-tube#56]
This is happening in using osmosis test tube with self hosted github actions.

```
error: failed to run custom build command for `osmosis-test-tube v25.0.0`
Error: note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/runner/_work/contracts/contracts/target/debug/build/osmosis-test-tube-2d398501ed9a8450/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=./libosmosistesttube

  --- stderr
  thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/osmosis-test-tube-25.0.0/build.rs:114:10:
  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
     2: core::result::unwrap_failed
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
     3: build_script_build::build_libosmosistesttube
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
```

**Comment by igorperic17** [comment]
Having the same issue here.

**Comment by igorperic17** [comment]
Turns out a simple `brew install go` solved it. Test tube needs go compiler installed in order to be built for your architecture. Hope this helps. :)
